# Generated by Django 5.0.1 on 2024-02-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_categoria_genero_producto_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='sistema.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='sistema.talla'),
        ),
    ]
